### PR TITLE
Added TwelveHourDateTimeConverter...

### PR DESCRIPTION
**Pull request by awj100**
... and implemented in Models.Response.TermbasedDetails.

### CODE REVIEW

**Comment by cromica** [comment]
Hi Andrew,

Can you please have a look at your changes. It seems they brake some of the current functionality.

**Comment by cromica** [comment]
Thanks for the reply. It looks to me that this should be fixed in GroupShare rather than in the client library. Let me check.

**Comment by awj100** [comment]
I totally agree. However, we need a working solution in a much more immediate time frame.

To this end we have implemented a solution for which I'll send you a pull request.

If and when a fix is implemented in GroupShare then our TwelveHourDateTimeConverter can simply be removed from the project and the JsonConverter attribute decorating Sdl.Community.GroupShareKit.Models.Response.TermbaseDetails.CreationDate can be removed.


________________________________

**Comment by awj100** [comment]
Closing this pull request as it has been superseded by another commit.

**Pull request closed without merging**
